# Generated by Django 5.1 on 2024-08-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement_data',
            new_name='created_at',
        ),
    ]
